# Generated by Django 2.2.9 on 2020-08-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemViagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Toral')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.Viagem')),
            ],
        ),
    ]
