# Generated by Django 2.2.5 on 2020-06-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=155, verbose_name='Produto')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso')),
                ('logradouro', models.CharField(max_length=155, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=155, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=155, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=155, verbose_name='Estado')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('local_descricao', models.CharField(max_length=155, verbose_name='Descrição do local')),
            ],
        ),
    ]
