# Generated by Django 2.2.9 on 2020-08-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_reboque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('reboque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.Reboque')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.Truck')),
            ],
        ),
    ]
