# Generated by Django 2.2.9 on 2020-08-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorista', '0001_initial'),
        ('veiculo', '0003_conjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Data e hora do inicio')),
                ('origem', models.CharField(max_length=155, verbose_name='Origem')),
                ('destino', models.CharField(max_length=155, verbose_name='Destino')),
                ('obs', models.TextField(verbose_name='Observações')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorista.Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.Reboque')),
            ],
        ),
    ]
