# Generated by Django 2.2.9 on 2020-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='alias',
            field=models.CharField(default=1, max_length=50, verbose_name='Alias'),
            preserve_default=False,
        ),
    ]
